# Starter pipeline
trigger:
  - main

pool:
  name: Default

steps:  
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.x'  # Adjust based on the SDK version you need
      installationPath: $(Agent.ToolsDirectory)/dotnet
      
  - script: |
      sudo apt-get update
      sudo apt-get install -y mono-complete
    displayName: "Install Mono"
    
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'  

  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet Package'
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'off'  # Disable automatic versioning
      configuration: 'Release'
      outputDirectory: '$(Build.ArtifactStagingDirectory)'
      arguments: '/p:PackageVersion=1.0.$(Build.BuildId)' 

  - task: DotNetCoreCLI@2
    inputs:
      command: 'push'
      artifactoryConnection: 'red'
      targetDeployRepo: 'continuous-nuget-local'
      pathToNupkg: '*.nupkg'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'

