# Starter pipeline
trigger:
  - main

pool:
  name: Default

steps:  
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.x'  # Adjust based on the SDK version you need
      installationPath: $(Agent.ToolsDirectory)/dotnet
      
  - script: |
      sudo apt-get update
      sudo apt-get install -y mono-complete
    displayName: "Install Mono"
    
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'  

      

  - task: JFrogNuGet@1
    inputs:
      command: 'push'
      artifactoryConnection: 'red'
      targetDeployRepo: 'continuous-nuget-local'
      pathToNupkg: '*.nupkg'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
