# Starter pipeline
trigger:
  - main

pool:
  name: Default

steps:  
  - task: JFrogNuGet@1
    inputs:
      command: 'restore'
      artifactoryConnection: 'red'
      targetResolveRepo: 'continuous-nuget'
      solutionPath: '**/*.sln'

  - task: JFrogNuGet@1
    inputs:
      command: 'push'
      artifactoryConnection: 'red'
      targetDeployRepo: 'continuous-nuget-local'
      pathToNupkg: '*.nupkg'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
